services:
  # HEA Webapp Service
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hea-webapp
    ports:
      - "8501:8501"
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./experiments:/app/experiments
      # Mount config for easy updates
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      - hea-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # HEA Backend API Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hea-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount models and config
      - ./models:/app/models
      - ./config:/app/config
      - ./backend/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=8000
    networks:
      - hea-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hea-network:
    driver: bridge

volumes:
  hea-data:
  hea-models:
  hea-logs:
